# Generated by Django 3.0.4 on 2020-04-11 16:04

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('extension_name', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=6, null=True)),
                ('birth_date', models.DateField()),
                ('school_status', models.BooleanField(default=True, verbose_name='schooling status')),
                ('image', models.ImageField(blank=True, null=True, upload_to=students.models.user_directory_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.StudentSchedule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
