# Generated by Django 3.0.4 on 2020-04-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentname_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentname',
            name='school_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.SchoolStatus', verbose_name='schooling status'),
        ),
    ]
