# Generated by Django 3.0.4 on 2020-04-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200415_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='school_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.SchoolStatus', verbose_name='schooling status'),
        ),
    ]
