# Generated by Django 3.0.4 on 2020-04-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_schoolstatus_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentname',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='studentname',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='studentname',
            name='schedule',
        ),
    ]
