# Generated by Django 3.0.4 on 2020-04-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_remove_scheduleadvice_student'),
        ('students', '0009_auto_20200417_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentname',
            name='advicing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleAdvice'),
        ),
    ]
