# Generated by Django 3.0.4 on 2020-04-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentname_advicing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentname',
            name='advicing',
        ),
    ]
