# Generated by Django 3.0.4 on 2020-04-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0017_delete_scheduleadvice'),
        ('students', '0011_remove_studentname_advicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentname',
            name='advice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentname',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentname',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule'),
        ),
    ]
