# Generated by Django 3.0.4 on 2020-04-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='user',
            new_name='adviser',
        ),
    ]
