# Generated by Django 3.0.4 on 2020-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum number of students'),
        ),
    ]
