# Generated by Django 3.0.4 on 2020-04-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_section_max_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='max_number',
        ),
    ]
