# Generated by Django 3.0.4 on 2020-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_remove_section_max_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_number',
            field=models.IntegerField(default=0, verbose_name='maximum number of students'),
        ),
        migrations.AddField(
            model_name='section',
            name='student_counter',
            field=models.IntegerField(default=0),
        ),
    ]
