# Generated by Django 3.0.4 on 2020-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_delete_studentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='max_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum number of students'),
        ),
    ]
