# Generated by Django 3.0.4 on 2020-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_max_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
