# Generated by Django 3.0.4 on 2020-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20200414_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='student_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
