# Generated by Django 3.0.4 on 2020-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_schedule_student_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='student_counter',
            field=models.IntegerField(default=0),
        ),
    ]
