# Generated by Django 3.0.4 on 2020-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20200415_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='max_number',
            field=models.IntegerField(default=0, verbose_name='maximum number of students'),
        ),
    ]
