# Generated by Django 3.0.4 on 2020-04-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20200415_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='max_number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='student_counter',
        ),
    ]
