# Generated by Django 3.0.4 on 2020-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20200415_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='max_number',
            field=models.IntegerField(default=0, verbose_name='maximum number of students'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_counter',
            field=models.IntegerField(default=0),
        ),
    ]
