# Generated by Django 3.0.4 on 2020-04-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_studentname_advicing'),
        ('schedules', '0015_remove_scheduleadvice_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleadvice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.StudentName'),
        ),
    ]
