# Generated by Django 3.0.4 on 2020-04-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_scheduleadvice_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAdvice',
        ),
    ]
