# Generated by Django 3.0.4 on 2020-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_auto_20200422_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectschedule',
            name='subject_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
