# Generated by Django 3.0.4 on 2020-04-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_auto_20200422_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadviceschedule',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.SubjectSchedule'),
        ),
    ]
