# Generated by Django 3.0.4 on 2020-04-22 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0022_auto_20200422_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(default='monday-friday', max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectschedule',
            name='max_number',
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.WeeklySchedule'),
        ),
    ]
