# Generated by Django 3.0.4 on 2020-04-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0023_auto_20200422_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectschedule',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.WeeklySchedule'),
        ),
    ]
