# Generated by Django 3.0.4 on 2020-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0024_auto_20200422_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='schedule',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
